GET http://localhost:8000/api/fetch/products
Authorization: Bearer 75e8cd5b-c49a-47e0-9bde-9f9b8ee15ec2

###

POST http://localhost:8000/api/auth/login 
Content-Type: application/json

{
  "username": "newuser",
  "password": "password123"
}

###

POST http://localhost:8000/api/logout

###

GET http://localhost:8000/api/cart/15